from langgraph.graph import StateGraph, END, START
from langgraph.types import Send
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from transformers import BlipProcessor, BlipForConditionalGeneration
from typing import TypedDict, Annotated, List, Literal
from pydantic import BaseModel, Field
from IPython.display import display
import operator
from pprint import pprint
from PIL import Image
import litellm
import sys
import re

api_key = "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"
captions = []
model_names = ["Salesforce/blip-image-captioning-base", "Salesforce/blip-image-captioning-large"]

for model_name in model_names:
    # Initialize the processor and model from Hugging Face
    processor = BlipProcessor.from_pretrained(model_name)
    model = BlipForConditionalGeneration.from_pretrained(model_name)
    file = sys.argv[1]
    # Load an image
    image = Image.open(file)
    # Prepare the image
    inputs = processor(image, return_tensors="pt")
    # Generate captions
    outputs = model.generate(**inputs)
    caption = processor.decode(outputs[0],skip_special_tokens=True)
    captions.append(caption)

print(captions[0])
print(captions[1])

llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.7, openai_api_key=api_key)

litellm.ssl_verify = False

class Caption(BaseModel):
    caption1: str = Field(..., description="Caption generated by one of the models")

class Captions(BaseModel):
    captions: List[Caption] = Field(..., description="List of captions generated by the models")

caption_prompt = ChatPromptTemplate.from_messages([
    "system", 
    "You are a helpful assistant that compares two image captions and selects the best one printing it to the console."
])

critic_pipe = caption_prompt | llm.with_structured_output(Captions)

critic_pipe.invoke({"captions": [{"caption1": captions[0]}, {"caption1": captions[1]}]})
